using Matterless.Inject;
using System.IO;
using UnityEngine;

namespace Matterless.Floorcraft.TestECS
{
    public class TestECSMain : MonoBehaviour
    {
        [SerializeField] RootContext m_RootContext;

        private void Awake()
        {
#if UNITY_EDITOR
            InitMermaidWriter();
#endif
            m_RootContext.StartContext();
        }
        private void InitMermaidWriter()
        {
            string parentPath = Directory.GetParent(Application.dataPath).FullName;
            string mermaidPath = Path.Combine(parentPath, "Docs", "TestECS");
            MermaidWriter.Init(mermaidPath, "Test ECS Dependencies Diagram (autogenerated)");
        }
    }
}