using Matterless.Inject;
using System.IO;
using UnityEngine;

namespace Matterless.Floorcraft
{
    public class Main : MonoBehaviour
    {
        [SerializeField] private RootContext m_RootContext;

        private void Awake()
        {
#if UNITY_EDITOR
            Application.quitting += () => Debug.Log("<color=magenta>QUITTING...</color>");
            InitMermaidWriter();
#endif
            m_RootContext.StartContext();
        }

        private void InitMermaidWriter()
        {
            var parentPath = Directory.GetParent(Application.dataPath).FullName;
            var mermaidPath = Path.Combine(parentPath, "Docs");
            MermaidWriter.Init(mermaidPath, "Floorcraft Dependencies Diagram (autogenerated)");
        }
        
        #if UNITY_EDITOR
        [ContextMenu("Clear PlayerPrefs")]
        private void ClearPlayerPrefs()
        {
            PlayerPrefs.DeleteAll();
            PlayerPrefs.Save();
        }
        #endif
    }
}
